Add dropdown menu to Config
thepieterdc/dodona-plugin-vscode pull request #13
Opened 2020-09-22 20:48 UTC by stijndcl

Added a dropdown menu to Config to change the submission platform to Naos or Dodona without having to change the link in the code every time

2020-09-23 09:14 UTC, thepieterdc requested changes

2020-09-23 09:14 UTC, thepieterdc commented on package.json
> +          "enum": ["Dodona", "Naos"],
```suggestion
          "default": "https://dodona.ugent.be",
          "enum": ["https://dodona.ugent.be", "https://naos.ugent.be"],
```

2020-09-23 09:14 UTC, thepieterdc commented on package.json
> +        "dodona.platform": {
```suggestion
        "dodona.api.host": {
```

2020-09-23 09:14 UTC, thepieterdc commented on package.json
> +          "description": "Specifies whether submissions should be sent to Dodona or Naos.",
```suggestion
          "description": "Specifies which Dodona instance should be used.",
```

2020-09-23 09:14 UTC, thepieterdc commented on src/extension.ts
> +            const post = bent(`https://${domain}.ugent.be`, 'POST', 'json');
By specifying the host in the settings directly (see previous remark), the domain does not need to be lowercased and can be used directly.
**Make sure to test if it still works, it's possible that `@ts-ignore` is still required anyway**

```suggestion
            const post = bent(config.get('api.host'), 'POST', 'json');
```

2020-09-23 10:05 UTC, stijndcl commented
Tested, still works as expected

2020-09-24 22:22 UTC, thepieterdc approved these changes

2020-09-24 22:22 UTC, merged