Comment syntax for new languages on Dodona added
thepieterdc/dodona-plugin-vscode pull request #252
Opened 2021-11-18 12:45 UTC by BTWS2

Closes #249.

2021-11-19 12:31 UTC, stijndcl requested changes
The order of the comment lambdas & languages was alphabetical. Now they aren't anymore. Can you put `exclamation` and `html` in the right place?

2021-11-19 12:37 UTC, BTWS2 commented
> The order of the comment lambdas & languages was alphabetical. Now they aren't anymore. Can you put `exclamation` and `html` in the right place?

Yes of course, didn't notice it at first. I changed it now.

2021-11-20 16:25 UTC, thepieterdc submitted a review, later dismissed

2021-11-20 16:28 UTC, thepieterdc approved these changes

2021-11-20 16:28 UTC, merged